use_frameworks!

platform :ios, '13.0'

target 'LuckySanbox_Example' do
  pod 'LuckySanbox', :path => '../'

  pod 'LuckyPop', :git => 'https://github.com/JunkyTang/LuckyPop.git'
  pod 'LuckyIB', :git => 'https://github.com/JunkyTang/LuckyIB.git'
  pod 'LuckyPropertyWrapper', :git => 'https://github.com/JunkyTang/LuckyPropertyWrapper.git'
  
  target 'LuckySanbox_Tests' do
    inherit! :search_paths
  end
end
